{
 "title": "MLOps Production Monitor",
 "description": "Supervision en temps réel de la santé, de la performance et de la fiabilité de l'API d'inférence Iris.",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Erreurs / Seconde",
   "type": "stat",
   "description": "Taux d'Erreur (Fiabilité)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status_code=\"400\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Utilisée",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Trafic Api",
   "type": "timeseries",
   "description": "Volume de requêtes reçues par l'API",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vitesse IA",
   "type": "gauge",
   "description": "La Vitesse de Réponse (Latence)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(prediction_latency_seconds_sum[5m]) / rate(prediction_latency_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}